version: '3'

services:
  texnoservisdb:
    container_name: texnoservisdb
    image: postgres
    environment:
      POSTGRES_DB: db_texnoservis
      POSTGRES_USER: texnoservisuser
      POSTGRES_PASSWORD: texnoservispass
    volumes:
      - postgres_data:/var/lib/postgresql/datatexnoservis/
    ports:
      - "5432:5432"
  texnoservisweb:
    container_name: texnoservis
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - texnoservisdb
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
